# Generated by Django 2.0 on 2019-06-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eamcetapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Email',
            field=models.EmailField(default='@gmail.com', max_length=254),
        ),
    ]
