# Generated by Django 2.0 on 2019-06-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eamcetapp', '0002_auto_20190621_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Col_Name', models.CharField(max_length=30)),
                ('Col_Code', models.CharField(max_length=20)),
                ('Col_Address', models.CharField(max_length=20)),
                ('University', models.CharField(max_length=30)),
                ('Rank', models.IntegerField()),
            ],
        ),
    ]
