# Generated by Django 2.0 on 2019-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eamcetapp', '0005_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegedata',
            old_name='Col_Address',
            new_name='College_Address',
        ),
        migrations.RenameField(
            model_name='collegedata',
            old_name='Col_Code',
            new_name='College_Code',
        ),
        migrations.RenameField(
            model_name='collegedata',
            old_name='Col_Name',
            new_name='College_Name',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='Pre_Col_Name',
            new_name='Previous_College_Name',
        ),
        migrations.RenameField(
            model_name='studentdata',
            old_name='Stu_Name',
            new_name='Student_Name',
        ),
        migrations.AlterField(
            model_name='collegedata',
            name='Rank_limit',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register',
            name='Rank',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Inter_Percent',
            field=models.FloatField(default=None),
        ),
    ]
